get:
  tags:
    - Produits
  summary: Obtenir la liste des produits possédés.
  description: Route permettant de visualiser l'ensemble des produits possédés (cartes, abonnements...), quantité et quantité assignée.
  operationId: products
  security: 
    - bearerAuth: []
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                examples:
                  - true
              subscription:
                type: object
                description: Données relatives aux abonnements.     
                properties:
                  product_name:
                    type: string
                    examples:
                      - "Abonnement premium"   
                  quantity:
                    type: integer
                    examples:
                    - 8
                  assigned_quantity: 
                    type: integer
                    examples:
                    - 7
              products:
                type: array
                description: Données relatives aux cartes.
                items:
                  properties:
                      product_name:
                    type: string
                    examples:
                      - "PVC Sur-mesure Profil-Manager - Blanche"   
                  quantity:
                    type: integer
                    examples:
                    - 4
                  assigned_quantity: 
                    type: integer
                    examples:
                    - 2
    '500':
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                examples:
                  - false
              message:
                type: string
                examples:
                  - "Nom d'utilisateur inconnu."
  x-codeSamples:
    - lang: C#
      source:
        $ref: ../code_samples/C_sharp/echo/post.cs
    - lang: PHP
      source:
        $ref: ../code_samples/PHP/echo/post.php