openapi: 3.1.0
info:
  version: 1.0.0
  title: Kipful API
  termsOfService: https://www.kipful.com/conditions-generales-dutilisation/
  contact:
    email: contact@kipful.com
    url: https://www.kipful.com/contact/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://i0.wp.com/www.kipful.com/wp-content/uploads/2020/08/KIPFUL-LOGO-NOIR-78x.png?fit=245%2C78&ssl=1
  description: >
    # Introduction

    Cette documentation a pour objectif de faciliter le développement de client autour de l'API proposée par Kipful.
    Il est impératif de posséder un profil manager spécifique à l'API pour pouvoir interagir avec celle-ci. 
    Si vous êtes intéressés par l'API, n'hésitez pas à prendre contact avec l'entreprise Kipful, soit sur le site https://www.kipful.com soit par email.
tags:
  - name: Authentification
    description: Routes d'authentification.
  - name: Utilisateurs
    description: Opérations autour des utilisateurs.
servers:
  # - url: https://www.kipful.com/wp-json # {tenant}
  #   variables:
  #     tenant:
  #       default: www
  #       description: Your tenant id
  - url: https://www.kipful.com/wp-json
paths:
  /api-bearer-auth/v1/login:
    $ref: paths/authentication.yaml
  /api/v1/users:
    $ref: paths/users.yaml
  /api/v1/user:
    $ref: paths/user.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
    bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
